---
- name: create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: "{{ gitkraken_download_dir }}"

- name: ensure ca-certificates installed
  become: yes
  apt:
    name: ca-certificates
    state: present

- name: download GitKraken
  get_url:
    url: "{{ gitkraken_redis_url }}"
    dest: "{{ gitkraken_download_dir }}/{{ gitkraken_redis_filename }}"
    force: no
    use_proxy: yes
    validate_certs: yes
    mode: 'u=rw,go=r'

- name: install GitKraken dependencies
  become: yes
  apt:
    name: gvfs-bin
    state: present

- name: install GitKraken
  become: yes
  apt:
    deb: "{{ gitkraken_download_dir }}/{{ gitkraken_redis_filename }}"
