---
- name: create local Ansible data directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: "{{ local_ansible_data_path }}"

- name: download GitKraken
  get_url:
    url: "{{ gitkraken_redis_url }}"
    dest: "{{ local_ansible_data_path }}/{{ gitkraken_redis_filename }}"
    force: false
    use_proxy: true
    validate_certs: true
    mode: 'u=rw,go=r'

- name: install GitKraken dependencies
  become: yes
  apt:
    name: gvfs-bin
    state: present

- name: install GitKraken
  become: yes
  apt:
    deb: "{{ local_ansible_data_path }}/{{ gitkraken_redis_filename }}"
